services:
  #--Chromadb --#
  chroma:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: always

  #--Jupyter Notebook --#
  ipython-notebook:
    container_name: MeuNotebook
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=/home/jovyan/work
      - CHOWN_EXTRA_OPTS=-R
    env_file:
      - .env
    restart: unless-stopped