services:
  #--Chromadb --#
  chroma:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: always

  #--Jupyter Notebook --#
  ipython-notebook:
    image: meu-jupyter-notebook
    container_name: Notebook
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    restart: unless-stopped